//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pemetaan_Ekonomi_Ketapang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pemetaan_Ekonomi_Ketapang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KKKetapang {
            get {
                object obj = ResourceManager.GetObject("KKKetapang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoKKetapang {
            get {
                object obj = ResourceManager.GetObject("LogoKKetapang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.05.1.0.0.
        /// </summary>
        internal static string versiAplikasi {
            get {
                return ResourceManager.GetString("versiAplikasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2E694F.
        /// </summary>
        internal static string warna1 {
            get {
                return ResourceManager.GetString("warna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D5D7C.
        /// </summary>
        internal static string warna2 {
            get {
                return ResourceManager.GetString("warna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFFFFF.
        /// </summary>
        internal static string warna3 {
            get {
                return ResourceManager.GetString("warna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF5939.
        /// </summary>
        internal static string warna4 {
            get {
                return ResourceManager.GetString("warna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WatermarkKeuskupanKetapang {
            get {
                object obj = ResourceManager.GetObject("WatermarkKeuskupanKetapang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
